import os
import pickle
from typing import Optional, List, Dict, Any, Tuple

import numpy as np
import pandas as pd
import httpx
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

# ------------------------------------------------------------
# Load environment variables from .env file
# ------------------------------------------------------------
load_dotenv()

# ------------------------------------------------------------
# TMDB Configuration
# ------------------------------------------------------------
TMDB_API_KEY = os.getenv("TMDB_API_KEY")

TMDB_BASE = "https://api.themoviedb.org/3"
TMDB_IMG_500 = "https://image.tmdb.org/t/p/w500"

# Ensure API key exists before application starts
if not TMDB_API_KEY:
    raise ValueError(
        "TMDB_API_KEY missing. Please set it in the .env file."
    )

# ------------------------------------------------------------
# FastAPI Application
# ------------------------------------------------------------
app = FastAPI(
    title="Movie Recommender API",
    version="1.0"
)

# Enable CORS so frontend applications
# (React, Streamlit, etc.) can access the API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ------------------------------------------------------------
# Local File Paths
# ------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

DF_PATH = os.path.join(BASE_DIR, "df.pkl")
INDICES_PATH = os.path.join(BASE_DIR, "indices.pkl")
TFIDF_MATRIX_PATH = os.path.join(BASE_DIR, "tfidf_matrix.pkl")
TFIDF_PATH = os.path.join(BASE_DIR, "tfidf.pkl")

# ------------------------------------------------------------
# Global Variables
# These will be loaded during application startup
# ------------------------------------------------------------
df: Optional[pd.DataFrame] = None
indices_obj: Any = None
tfidf_matrix: Any = None
tfidf_obj: Any = None

TITLE_TO_IDX: Optional[Dict[str, int]] = None

# ------------------------------------------------------------
# Pydantic Models
# ------------------------------------------------------------


class TMDBMovieCard(BaseModel):
    """
    Lightweight movie representation used for:
    - Search results
    - Recommendation cards
    - Movie grids
    """

    tmdb_id: int
    title: str
    poster_url: Optional[str] = None
    release_date: Optional[str] = None
    vote_average: Optional[float] = None


class TMDBMovieDetails(BaseModel):
    """
    Detailed movie information returned when
    a user selects a specific movie.
    """

    tmdb_id: int
    title: str
    overview: Optional[str] = None
    release_date: Optional[str] = None
    poster_url: Optional[str] = None
    backdrop_url: Optional[str] = None
    genres: List[dict] = []


class TFIDFRecItem(BaseModel):
    """
    Recommendation item generated by the
    TF-IDF recommendation engine.
    """

    title: str
    score: float
    tmdb: Optional[TMDBMovieCard] = None


class SearchBundleResponse(BaseModel):
    """
    Complete response object returned by
    recommendation endpoints.
    """

    query: str
    movie_details: TMDBMovieDetails
    tfidf_recommendation: List[TFIDFRecItem]
    genre_recommendation: List[TMDBMovieCard]


# ------------------------------------------------------------
# Helper Functions
# ------------------------------------------------------------

def _norm_title(t: str) -> str:
    """
    Normalize a movie title for consistent matching.

    Operations:
    - Convert to string
    - Remove leading/trailing spaces
    - Convert to lowercase

    Example:
        "  Inception  " -> "inception"

    Args:
        t (str): Movie title.

    Returns:
        str: Normalized title.
    """
    return str(t).strip().lower()


def make_img_url(path: Optional[str]) -> Optional[str]:
    """
    Convert a TMDB image path into a complete URL.

    Example:
        Input:
            /abc123.jpg

        Output:
            https://image.tmdb.org/t/p/w500/abc123.jpg

    Args:
        path (Optional[str]): TMDB image path.

    Returns:
        Optional[str]:
            Complete image URL if path exists,
            otherwise None.
    """
    if not path:
        return None

    return f"{TMDB_IMG_500}{path}"


# ------------------------------------------------------------
# TMDB API Functions
# ------------------------------------------------------------

async def tmdb_get(
    path: str,
    params: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Generic helper function for making GET requests
    to the TMDB API.

    Responsibilities:
    - Add API key automatically
    - Handle network errors
    - Validate response status

    Args:
        path (str):
            TMDB endpoint path.

        params (Dict[str, Any]):
            Query parameters.

    Returns:
        Dict[str, Any]:
            JSON response from TMDB.

    Raises:
        HTTPException:
            502 if TMDB request fails.
    """

    q = dict(params)
    q["api_key"] = TMDB_API_KEY

    try:
        async with httpx.AsyncClient(timeout=20) as client:
            r = await client.get(
                f"{TMDB_BASE}{path}",
                params=q
            )

    except httpx.RequestError as e:
        raise HTTPException(
            status_code=502,
            detail=(
                f"TMDB request error: "
                f"{type(e).__name__} | {repr(e)}"
            ),
        )

    if r.status_code != 200:
        raise HTTPException(
            status_code=502,
            detail=f"TMDB error {r.status_code}: {r.text}",
        )

    return r.json()


async def tmdb_cards_from_results(
    results: List[dict],
    limit: int = 20
) -> List[TMDBMovieCard]:
    """
    Convert raw TMDB search results into
    lightweight movie cards.

    Useful for:
    - Search results
    - Recommendation sections
    - Movie listing pages

    Args:
        results (List[dict]):
            Raw movie objects from TMDB.

        limits (int):
            Maximum number of cards to return.

    Returns:
        List[TMDBMovieCard]:
            Processed movie card objects.
    """

    out: List[TMDBMovieCard] = []

    for m in (results or [])[:limit]:
        out.append(
            TMDBMovieCard(
                tmdb_id=int(m["id"]),
                title=m.get("title")
                or m.get("name")
                or "",
                poster_url=make_img_url(
                    m.get("poster_path")
                ),
                release_date=m.get("release_date"),
                vote_average=m.get("vote_average"),
            )
        )

    return out


async def tmdb_movie_details(
    movie_id: int
) -> TMDBMovieDetails:
    """
    Fetch detailed information about a movie.

    Includes:
    - Overview
    - Poster
    - Backdrop
    - Genres
    - Release date

    Args:
        movie_id (int):
            TMDB movie ID.

    Returns:
        TMDBMovieDetails:
            Detailed movie information.
    """

    data = await tmdb_get(
        f"/movie/{movie_id}",
        {"language": "en-US"}
    )

    return TMDBMovieDetails(
        tmdb_id=int(data["id"]),
        title=data.get("title") or "",
        overview=data.get("overview"),
        release_date=data.get("release_date"),
        poster_url=make_img_url(
            data.get("poster_path")
        ),
        backdrop_url=make_img_url(
            data.get("backdrop_path")
        ),
        genres=data.get("genres", []) or [],
    )


async def tmdb_search_movies(
    query: str,
    page: int = 1
) -> Dict[str, Any]:
    """
    Search TMDB using a movie title or keyword.

    Used by:
    - Search box
    - Suggestions
    - Discovery pages

    Args:
        query (str):
            Movie title or keyword.

        page (int):
            TMDB page number.

    Returns:
        Dict[str, Any]:
            Raw TMDB search response.
    """

    return await tmdb_get(
        "/search/movie",
        {
            "query": query,
            "include_adult": "false",
            "language": "en-US",
            "page": page,
        },
    )


async def tmdb_search_first(
    query: str
) -> Optional[dict]:
    """
    Search TMDB and return the first match.

    This is useful when the user provides
    a movie title and we want the most
    relevant result immediately.

    Args:
        query (str):
            User-entered movie title.

    Returns:
        Optional[dict]:
            First movie result if found,
            otherwise None.
    """

    data = await tmdb_search_movies(
        query=query,
        page=1
    )

    results = data.get("results", [])

    return results[0] if results else None



def build_title_to_idx_map(indices: Any) -> Dict[str,int]:
    """
    indices.pkl can be:
    - dict(title-> index)
    - pandas Series(index = title, value = index)
    We normalise into TITLE_TO_IDX
    """
    title_to_idx: Dict[str,int] = {}

    if isinstance(indices, dict):
        for k , v in indices.items():
            title_to_idx[_norm_title(k)] = int(v)
        return title_to_idx


    # Pandas series or similar mapping
    try:
        for k , v in indices.items():
            title_to_idx[_norm_title(k)] = int(v)
        return title_to_idx
    except Exception:
        # Last resort: if its a list - like etc.
        raise RuntimeError(
            "indices.pkl must be dict or pandas Series-like (with .items())"
        )
    


def get_local_idx_by_title(title:  str) -> int:
    global TITLE_TO_IDX
    if TITLE_TO_IDX is None:
        raise HTTPException(status_code = 500, detail = "TF-IDF index map not initialised")
    key = _norm_title(title)
    if key in TITLE_TO_IDX:
        return int(TITLE_TO_IDX[key])
    raise HTTPException(
        status_code = 404, detail = f"Title not found in local dataset: '{title}' "
    )


def tfidf_recommend_titles(
    query_title: str, top_n: int = 10
) -> List[Tuple[str, float]]:
    """
    Returns list of (title, score) from local df using cosine similarity on TF-IDF matrix.
    Safe against missing columns/rows.
    """
    global df, tfidf_matrix
    if df is None or tfidf_matrix is None:
        raise HTTPException(status_code=500, detail="TF-IDF resources not loaded")

    idx = get_local_idx_by_title(query_title)

    # query vector
    qv = tfidf_matrix[idx]
    scores = (tfidf_matrix @ qv.T).toarray().ravel()

    # sort descending
    order = np.argsort(-scores)

    out: List[Tuple[str, float]] = []
    for i in order:
        if int(i) == int(idx):
            continue
        try:
            title_i = str(df.iloc[int(i)]["title"])
        except Exception:
            continue
        out.append((title_i, float(scores[int(i)])))
        if len(out) >= top_n:
            break
    return out


async def attach_tmdb_card_by_title(title: str) -> Optional[TMDBMovieCard]:
    """
    Uses TMDB search by title to fetch poster for a local title.
    If not found, returns None (never crashes the endpoint).
    """
    try:
        m = await tmdb_search_first(title)
        if not m:
            return None
        return TMDBMovieCard(
            tmdb_id=int(m["id"]),
            title=m.get("title") or title,
            poster_url=make_img_url(m.get("poster_path")),
            release_date=m.get("release_date"),
            vote_average=m.get("vote_average"),
        )
    except Exception:
        return None
    


# =========================
# STARTUP: LOAD PICKLES
# =========================
@app.on_event("startup")
def load_pickles():
    global df, indices_obj, tfidf_matrix, tfidf_obj, TITLE_TO_IDX

    # Load df
    with open(DF_PATH, "rb") as f:
        df = pickle.load(f)

    # Load indices
    with open(INDICES_PATH, "rb") as f:
        indices_obj = pickle.load(f)

    # Load TF-IDF matrix (usually scipy sparse)
    with open(TFIDF_MATRIX_PATH, "rb") as f:
        tfidf_matrix = pickle.load(f)

    # Load tfidf vectorizer (optional, not used directly here)
    with open(TFIDF_PATH, "rb") as f:
        tfidf_obj = pickle.load(f)

    # Build normalized map
    TITLE_TO_IDX = build_title_to_idx_map(indices_obj)

    # sanity
    if df is None or "title" not in df.columns:
        raise RuntimeError("df.pkl must contain a DataFrame with a 'title' column")
    


# =========================
# ROUTES
# =========================
@app.get("/health")
def health():
    return {"status": "ok"}


# ---------- HOME FEED (TMDB) ----------
@app.get("/home", response_model=List[TMDBMovieCard])
async def home(
    category: str = Query("popular"),
    limit: int = Query(24, ge=1, le=50),
):
    """
    Home feed for Streamlit (posters).
    category:
      - trending (trending/movie/day)
      - popular, top_rated, upcoming, now_playing  (movie/{category})
    """
    try:
        if category == "trending":
            data = await tmdb_get("/trending/movie/day", {"language": "en-US"})
            return await tmdb_cards_from_results(data.get("results", []), limit=limit)

        if category not in {"popular", "top_rated", "upcoming", "now_playing"}:
            raise HTTPException(status_code=400, detail="Invalid category")

        data = await tmdb_get(f"/movie/{category}", {"language": "en-US", "page": 1})
        return await tmdb_cards_from_results(data.get("results", []), limit=limit)

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Home route failed: {e}")

# ---------- TMDB KEYWORD SEARCH (MULTIPLE RESULTS) ----------
@app.get("/tmdb/search")
async def tmdb_search(
    query: str = Query(..., min_length=1),
    page: int = Query(1, ge=1, le=10),
):
    """
    Returns RAW TMDB shape with 'results' list.
    Streamlit will use it for:
      - dropdown suggestions
      - grid results
    """
    return await tmdb_search_movies(query=query, page=page)


# ---------- MOVIE DETAILS (SAFE ROUTE) ----------
@app.get("/movie/id/{tmdb_id}", response_model=TMDBMovieDetails)
async def movie_details_route(tmdb_id: int):
    return await tmdb_movie_details(tmdb_id)


# ---------- GENRE RECOMMENDATIONS ----------
@app.get("/recommend/genre", response_model=List[TMDBMovieCard])
async def recommend_genre(
    tmdb_id: int = Query(...),
    limit: int = Query(18, ge=1, le=50),
):
    """
    Given a TMDB movie ID:
    - fetch details
    - pick first genre
    - discover movies in that genre (popular)
    """
    details = await tmdb_movie_details(tmdb_id)
    if not details.genres:
        return []

    genre_id = details.genres[0]["id"]
    discover = await tmdb_get(
        "/discover/movie",
        {
            "with_genres": genre_id,
            "language": "en-US",
            "sort_by": "popularity.desc",
            "page": 1,
        },
    )
    cards = await tmdb_cards_from_results(discover.get("results", []), limits=limit)
    return [c for c in cards if c.tmdb_id != tmdb_id]


# ---------- TF-IDF ONLY (debug/useful) ----------
@app.get("/recommend/tfidf")
async def recommend_tfidf(
    title: str = Query(..., min_length=1),
    top_n: int = Query(10, ge=1, le=50),
):
    recs = tfidf_recommend_titles(title, top_n=top_n)
    return [{"title": t, "score": s} for t, s in recs]


# ---------- BUNDLE: Details + TF-IDF recs + Genre recs ----------
@app.get("/movie/search", response_model=SearchBundleResponse)
async def search_bundle(
    query: str = Query(..., min_length=1),
    tfidf_top_n: int = Query(12, ge=1, le=30),
    genre_limit: int = Query(12, ge=1, le=30),
):
    """
    This endpoint is for when you have a selected movie and want:
      - movie details
      - TF-IDF recommendations (local) + posters
      - Genre recommendations (TMDB) + posters

    NOTE:
    - It selects the BEST match from TMDB for the given query.
    - If you want MULTIPLE matches, use /tmdb/search
    """
    best = await tmdb_search_first(query)
    if not best:
        raise HTTPException(
            status_code=404, detail=f"No TMDB movie found for query: {query}"
        )

    tmdb_id = int(best["id"])
    details = await tmdb_movie_details(tmdb_id)

    # 1) TF-IDF recommendations (never crash endpoint)
    tfidf_items: List[TFIDFRecItem] = []

    recs: List[Tuple[str, float]] = []
    try:
        # try local dataset by TMDB title
        recs = tfidf_recommend_titles(details.title, top_n=tfidf_top_n)
    except Exception:
        # fallback to user query
        try:
            recs = tfidf_recommend_titles(query, top_n=tfidf_top_n)
        except Exception:
            recs = []

    for title, score in recs:
        card = await attach_tmdb_card_by_title(title)
        tfidf_items.append(TFIDFRecItem(title=title, score=score, tmdb=card))

     # 2) Genre recommendations (TMDB discover by first genre)
    genre_recs: List[TMDBMovieCard] = []
    if details.genres:
        genre_id = details.genres[0]["id"]
        discover = await tmdb_get(
            "/discover/movie",
            {
                "with_genres": genre_id,
                "language": "en-US",
                "sort_by": "popularity.desc",
                "page": 1,
            },
        )
        cards = await tmdb_cards_from_results(
            discover.get("results", []), limits=genre_limit
        )
        genre_recs = [c for c in cards if c.tmdb_id != details.tmdb_id]

    return SearchBundleResponse(
        query=query,
        movie_details=details,
        tfidf_recommendations=tfidf_items,
        genre_recommendations=genre_recs,
    )

